spring:
  datasource:
    url: ENC(qzNo5V6cA2K5PaJPKl1tBKKHDCkil2CfE1YxW8CkejICOrhB/sv8KOtL3fJRbVAsFo1+e6FyJ9CheykY5TRyHqSVvzy8P+7XNp1YShj2hG5xqd3el5Ec1Sy06i9PrumGXRi/TKfdSZGlfMuLQi9cFEDIRvXPWFt7v4YMJTX5u3+qfis8fGFXUQ==)
    username: ENC(Udb4l5DfsmqofWab//2WIA==)
    password: ENC(rpGTUKqoHXoOD+0bgKtpiY6KswWmBZX2)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      connection-timeout: 60000
      maximum-pool-size: 5


elasticsearch:
  url: ENC(+fN++aKcc0BbzEd81Nv2SLM0xBp9Ocx8Nw/voDThdwVd/Nm4BxX8mCNlsAKNml4J)
google:
  key: ENC(RXZTJ7QPZ+Gueck4qiUvm5/G+MWoeU5fXT3KMtHk4O0lUpTi6zwT2JWO+n8oJ8kO)
naver:
  id: ENC(9v4pM1mTrHac38Rd+sQCp5gBQZkAX+/U0MVvdA/JnXE=)
  secret: ENC(AEo6hu3XfpfBZ4PaS3NYtJp5XQ1BI8rF)